`timescale 1ns/1ps

module digit_convolution_chunked #(
    parameter IMAGE_W        = 64,
    parameter IMAGE_H        = 64,
    parameter KERNEL_W       = 9,
    parameter KERNEL_H       = 13,
    parameter MAX_CHUNK_ROWS = 28,
    parameter THRESHOLD      = 8'd128
)(
    input  wire              clk,
    input  wire              rst,

    // Four grayscale pixels are packed into each word:
    // pixel 0 -> [31:24], pixel 1 -> [23:16],
    // pixel 2 -> [15:8],  pixel 3 -> [7:0].
    input  wire              word_valid,
    input  wire [31:0]       word_data,
    output wire              word_ready,

    // Pulses generated by the AXI control register.
    input  wire              new_image,
    input  wire              chunk_start,

    // Chunk metadata. Chunks are horizontal image strips.
    input  wire [5:0]        chunk_base_row,
    input  wire [5:0]        chunk_rows,
    input  wire [5:0]        scan_rows,
    input  wire              last_chunk,

    output reg               busy,
    output reg               chunk_done,
    output reg               done,
    output reg               error,
    output reg [8:0]         loaded_words,

    output reg [5:0]         digit8_x,
    output reg [5:0]         digit8_y,
    output reg signed [15:0] digit8_score,

    output reg [5:0]         digit9_x,
    output reg [5:0]         digit9_y,
    output reg signed [15:0] digit9_score
);

    localparam WORDS_PER_ROW  = IMAGE_W / 4;
    localparam MAX_CHUNK_WORDS = MAX_CHUNK_ROWS * WORDS_PER_ROW;
    localparam MAX_SCAN_X      = IMAGE_W - KERNEL_W;
    localparam MAX_SCAN_Y      = IMAGE_H - KERNEL_H;

    localparam STATE_LOAD        = 2'd0;
    localparam STATE_PIXEL_READ  = 2'd1;
    localparam STATE_PIXEL_ACCUM = 2'd2;

    // Bit index = row * KERNEL_W + column.
    localparam [KERNEL_W*KERNEL_H-1:0] TEMPLATE_8 =
        117'h0001C3F198C6663F0F8CC663F0F000;

    localparam [KERNEL_W*KERNEL_H-1:0] TEMPLATE_9 =
        117'h0001E1F9C0FC7F399CCE6331F03000;

    // 448 x 32 bits = 14336 bits when MAX_CHUNK_ROWS is 28.
    // The clocked read/write style is intended to infer block RAM.
    reg [31:0] chunk_mem [0:MAX_CHUNK_WORDS-1];

    reg [1:0] state;

    reg [5:0] active_chunk_base_row;
    reg [5:0] active_scan_rows;
    reg       active_last_chunk;

    reg [5:0] scan_x;
    reg [5:0] scan_y;
    reg [3:0] kernel_row;
    reg [3:0] kernel_col;

    reg signed [15:0] score8_accum;
    reg signed [15:0] score9_accum;

    reg [31:0] mem_rdata;
    reg [1:0]  pixel_lane_d;
    reg [6:0]  template_index_d;

    reg [7:0] selected_pixel;

    wire [9:0] expected_words;
    wire [6:0] current_pixel_row;
    wire [6:0] current_pixel_col;
    wire [8:0] current_word_address;
    wire [6:0] current_template_index;

    wire pixel_is_dark;
    wire signed [15:0] pixel_score8;
    wire signed [15:0] pixel_score9;
    wire signed [15:0] score8_next;
    wire signed [15:0] score9_next;

    assign expected_words = ({4'd0, chunk_rows} << 4);

    assign word_ready = (state == STATE_LOAD) &&
                        !done &&
                        (loaded_words < MAX_CHUNK_WORDS);

    assign current_pixel_row = {1'b0, scan_y} + kernel_row;
    assign current_pixel_col = {1'b0, scan_x} + kernel_col;

    assign current_word_address =
        {current_pixel_row[4:0], 4'b0000} + current_pixel_col[5:2];

    assign current_template_index = (kernel_row * KERNEL_W) + kernel_col;

    always @(*) begin
        case (pixel_lane_d)
            2'd0: selected_pixel = mem_rdata[31:24];
            2'd1: selected_pixel = mem_rdata[23:16];
            2'd2: selected_pixel = mem_rdata[15:8];
            default: selected_pixel = mem_rdata[7:0];
        endcase
    end

    assign pixel_is_dark = (selected_pixel < THRESHOLD);

    assign pixel_score8 = pixel_is_dark ?
                          (TEMPLATE_8[template_index_d] ? 16'sd1 : -16'sd1) :
                          16'sd0;

    assign pixel_score9 = pixel_is_dark ?
                          (TEMPLATE_9[template_index_d] ? 16'sd1 : -16'sd1) :
                          16'sd0;

    assign score8_next = score8_accum + pixel_score8;
    assign score9_next = score9_accum + pixel_score9;

    always @(posedge clk) begin
        if (rst) begin
            state                 <= STATE_LOAD;
            active_chunk_base_row <= 6'd0;
            active_scan_rows      <= 6'd0;
            active_last_chunk     <= 1'b0;

            scan_x       <= 6'd0;
            scan_y       <= 6'd0;
            kernel_row   <= 4'd0;
            kernel_col   <= 4'd0;
            score8_accum <= 16'sd0;
            score9_accum <= 16'sd0;

            mem_rdata       <= 32'd0;
            pixel_lane_d     <= 2'd0;
            template_index_d <= 7'd0;

            busy         <= 1'b0;
            chunk_done   <= 1'b0;
            done         <= 1'b0;
            error        <= 1'b0;
            loaded_words <= 9'd0;

            digit8_x     <= 6'd0;
            digit8_y     <= 6'd0;
            digit8_score <= 16'sh8000;

            digit9_x     <= 6'd0;
            digit9_y     <= 6'd0;
            digit9_score <= 16'sh8000;
        end else if (new_image) begin
            state                 <= STATE_LOAD;
            active_chunk_base_row <= 6'd0;
            active_scan_rows      <= 6'd0;
            active_last_chunk     <= 1'b0;

            scan_x       <= 6'd0;
            scan_y       <= 6'd0;
            kernel_row   <= 4'd0;
            kernel_col   <= 4'd0;
            score8_accum <= 16'sd0;
            score9_accum <= 16'sd0;

            busy         <= 1'b0;
            chunk_done   <= 1'b0;
            done         <= 1'b0;
            error        <= 1'b0;
            loaded_words <= 9'd0;

            digit8_x     <= 6'd0;
            digit8_y     <= 6'd0;
            digit8_score <= 16'sh8000;

            digit9_x     <= 6'd0;
            digit9_y     <= 6'd0;
            digit9_score <= 16'sh8000;
        end else begin
            case (state)
                STATE_LOAD: begin
                    busy <= 1'b0;

                    if (word_valid && word_ready) begin
                        chunk_mem[loaded_words] <= word_data;
                        loaded_words <= loaded_words + 9'd1;
                        chunk_done <= 1'b0;
                    end

                    if (chunk_start) begin
                        chunk_done <= 1'b0;

                        if ((chunk_rows < KERNEL_H) ||
                            (chunk_rows > MAX_CHUNK_ROWS) ||
                            (scan_rows == 0) ||
                            (scan_rows > (chunk_rows - KERNEL_H + 1)) ||
                            (({1'b0, chunk_base_row} + {1'b0, chunk_rows}) > IMAGE_H) ||
                            (({1'b0, chunk_base_row} + {1'b0, scan_rows}) > (MAX_SCAN_Y + 1)) ||
                            ({1'b0, loaded_words} != expected_words)) begin
                            error <= 1'b1;
                        end else begin
                            active_chunk_base_row <= chunk_base_row;
                            active_scan_rows      <= scan_rows;
                            active_last_chunk     <= last_chunk;

                            scan_x       <= 6'd0;
                            scan_y       <= 6'd0;
                            kernel_row   <= 4'd0;
                            kernel_col   <= 4'd0;
                            score8_accum <= 16'sd0;
                            score9_accum <= 16'sd0;

                            busy  <= 1'b1;
                            state <= STATE_PIXEL_READ;
                        end
                    end
                end

                STATE_PIXEL_READ: begin
                    mem_rdata <= chunk_mem[current_word_address];
                    pixel_lane_d <= current_pixel_col[1:0];
                    template_index_d <= current_template_index;
                    state <= STATE_PIXEL_ACCUM;
                end

                STATE_PIXEL_ACCUM: begin
                    if ((kernel_row == KERNEL_H - 1) &&
                        (kernel_col == KERNEL_W - 1)) begin

                        if (score8_next > digit8_score) begin
                            digit8_score <= score8_next;
                            digit8_x <= scan_x + (KERNEL_W / 2);
                            digit8_y <= active_chunk_base_row +
                                        scan_y + (KERNEL_H / 2);
                        end

                        if (score9_next > digit9_score) begin
                            digit9_score <= score9_next;
                            digit9_x <= scan_x + (KERNEL_W / 2);
                            digit9_y <= active_chunk_base_row +
                                        scan_y + (KERNEL_H / 2);
                        end

                        kernel_row   <= 4'd0;
                        kernel_col   <= 4'd0;
                        score8_accum <= 16'sd0;
                        score9_accum <= 16'sd0;

                        if ((scan_x == MAX_SCAN_X) &&
                            (scan_y == active_scan_rows - 1'b1)) begin
                            busy         <= 1'b0;
                            chunk_done   <= 1'b1;
                            loaded_words <= 9'd0;
                            state        <= STATE_LOAD;

                            if (active_last_chunk)
                                done <= 1'b1;
                        end else begin
                            if (scan_x == MAX_SCAN_X) begin
                                scan_x <= 6'd0;
                                scan_y <= scan_y + 6'd1;
                            end else begin
                                scan_x <= scan_x + 6'd1;
                            end

                            state <= STATE_PIXEL_READ;
                        end
                    end else begin
                        score8_accum <= score8_next;
                        score9_accum <= score9_next;

                        if (kernel_col == KERNEL_W - 1) begin
                            kernel_col <= 4'd0;
                            kernel_row <= kernel_row + 4'd1;
                        end else begin
                            kernel_col <= kernel_col + 4'd1;
                        end

                        state <= STATE_PIXEL_READ;
                    end
                end

                default: begin
                    state <= STATE_LOAD;
                end
            endcase
        end
    end

endmodule
